drop database BRAWAN; 

CREATE database BRAWAN; 

USE BRAWAN; 

CREATE TABLE IF NOT EXISTS CLIENTE(

ID BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
RG CHAR(30),
CPF CHAR(30),
SEXO VARCHAR(15),
TELEFONE VARCHAR(80),
EMAIL VARCHAR(150),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(80),
UF CHAR(2),
CEP CHAR(9),
TG_STATUS INT(1),
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO(

ID BIGINT NOT NULL AUTO_INCREMENT,
NOME  VARCHAR(100),
QUANTIDADE INTEGER,
CATEGORIA CHAR(15),
MARCA CHAR(15),
TAMANHO CHAR(15),
VL_UNITARIO varchar(10),
DESCRICAO VARCHAR(150),
TG_STATUS INT(1),
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LOGIN(
ID BIGINT NOT NULL AUTO_INCREMENT,
USUARIO VARCHAR(150),
SENHA VARCHAR(150),
PRIMARY KEY(ID)
);



CREATE TABLE IF NOT EXISTS EMPRESA (

ID BIGINT NOT NULL AUTO_INCREMENT,
EMPRESA  VARCHAR(100),
DIRETOR  VARCHAR(100),
CNPJ CHAR(30),
TELEFONE VARCHAR(80),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(80),
UF CHAR(2),
CEP CHAR(9),
EMAIL VARCHAR(150),
TG_STATUS CHAR(1),
PRIMARY KEY (ID)
);


CREATE TABLE IF NOT EXISTS FUNCIONARIO (

ID BIGINT NOT NULL AUTO_INCREMENT,
LOGIN VARCHAR(150),
SENHA VARCHAR(150),
NOME  VARCHAR(100),
RG CHAR(30),
CPF CHAR(30),
TELEFONE VARCHAR(80),
ENDERECO VARCHAR(120),
BAIRRO VARCHAR(60),
CIDADE VARCHAR(80),
UF CHAR(2),
CEP CHAR(9),
EMAIL VARCHAR(150),
SEXO VARCHAR(15),
CARGO VARCHAR(100),
EMPRESA VARCHAR(60),
FK_EMPRESA BIGINT NOT NULL,
TG_STATUS INT(1),
PRIMARY KEY (ID),
FOREIGN KEY (FK_EMPRESA) REFERENCES EMPRESA (ID)
);

INSERT INTO CLIENTE
(NOME,RG,CPF,SEXO,TELEFONE,EMAIL,ENDERECO,BAIRRO,CIDADE,UF,CEP,TG_STATUS)
VALUES ('BRUNINHO','1111111','222.333.444.55','MASCULINO','11997917090','BRUNO@YAHOO.COM','RUA SANTOS,123','SAO CARLOS','CARAPICUIBA','SP','00111.222',0);

INSERT INTO PRODUTO
(NOME,QUANTIDADE,CATEGORIA,MARCA,TAMANHO,VL_UNITARIO,DESCRICAO,TG_STATUS)
VALUES ('POLO NIKE BRANCO','22','POLO','NIKE','GG','129.99','POLO BRANCO',0);

INSERT INTO LOGIN (USUARIO,SENHA) VALUES('ADMIN','1234');
